export const resources=[
["Site agence","Voyageurs","Site","/","Préparation en accès restreint"],
["Collection","Voyageurs","Page","/collection","À compléter : logements"],
["LP Airbnb / Booking","Propriétaires Airbnb","Page","/proprietaires/airbnb","Préparation en accès restreint"],
["LP longue durée","Propriétaires longue durée","Page","/proprietaires/longue-duree","Préparation en accès restreint"],
["Formulaire d’étude","Propriétaires","Formulaire","/etude","Enregistrement serveur"],
["CRM et historique","Kevin","Outil","/pilotage","Accès Kevin uniquement"],
["Funnel commercial","Équipe","Outil","/interne/funnel","Supports disponibles"],
["Kit historique (15 sections)","Kevin","Document","/pilotage/ressources","Archive : segmentation ancienne"],
["Guide démo Saint-Cyprien","Équipe","Démonstration","/bienvenue/demo-saint-cyprien","Démonstration"],
["Guide démo Capitole","Équipe","Démonstration","/bienvenue/demo-capitole","Démonstration"],
["Gérer les guides","Kevin","Outil","/interne/logements","Édition serveur"],
["Présentation Solaya","Équipe","PDF","/documents/presentation.pdf","Modèle à compléter"],
["Étude Airbnb","Équipe","PDF","/documents/etude-airbnb.pdf","Modèle à compléter"],
["Étude longue durée","Équipe","PDF","/documents/etude-longue-duree.pdf","Modèle à compléter"],
["Proposition commerciale","Équipe","PDF","/documents/proposition.pdf","Modèle à compléter"],
["Sources modifiables des PDF","Équipe","Source","/documents/modeles.json","Document disponible"],
["Document commercial V3","Équipe","Document","https://docs.google.com/document/d/1NPfGZk4JzrEwjAoKI9ptjFUHqXkEFvqFvPTeWB5bZYY/edit","Document disponible"],
["Décisions et préparation","Équipe","Document","/interne/lancement","À compléter"],
];